version: '3'
services:
  postgres:
    image: postgres:15
    container_name: sequelize-backend-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5433}:5432

  postgres-test:
    image: postgres:15
    container_name: sequelize-backend-test-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD:-postgres}
    ports:
      - ${DB_TEST_PORT:-5434}:5432
